### ISSUE TITLE
mp3文件不能读取（？）

### ISSUE THREAD

**Issue by jcjrobert** [lgc-NB2Dev/nonebot-plugin-ottohzys#1]
读取原声大碟会报错
soundfile.LibsndfileError: Error opening <_io.BytesIO object at 0x7fd473fd7590>: File contains data in an unknown format.

转后缀为.wav且固定后缀为.wav后恢复正常

**Comment by lgc2333** [comment]
还有问题吗，今天才看到issue，我这没问题

**Comment by jcjrobert** [comment]
> 还有问题吗，今天才看到issue，我这没问题

我一直用的wav（）

**Comment by XieXiLin2** [comment]
> > 还有问题吗，今天才看到issue，我这没问题
> 
> 我一直用的wav（）

现在试试看 mp3 能不能正常用？

**Comment by jcjrobert** [comment]
先关了，后面有问题再开（主打一个能跑就行）
