### ISSUE TITLE
使用 ottohzys 指令无反应

### ISSUE THREAD

**Issue by viondw** [lgc-NB2Dev/nonebot-plugin-ottohzys#4]
☑我确定别的插件可以正常工作。

☑pyproject.toml中添加了该插件并重启运行也无反应。

控制台没有返回相关日志

**Comment by lgc2333** [comment]
插件加载时是否有报错？

**Comment by viondw** [comment]
安装日志
‘’‘
C:\Users\Administrator\Desktop\112\miraibot>nb plugin install nonebot-plugin-ott
ohzys
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: nonebot-plugin-ottohzys in c:\users\administrator
\appdata\local\programs\python\python310\lib\site-packages (0.2.0)
Requirement already satisfied: nonebot2>=2.2.0 in c:\users\administrator\appdata
\local\programs\python\python310\lib\site-packages (from nonebot-plugin-ottohzys
) (2.2.1)
Requirement already satisfied: nonebot-plugin-alconna>=0.40.0rc1 in c:\users\adm
inistrator\appdata\local\programs\python\python310\lib\site-packages (from noneb
ot-plugin-ottohzys) (0.41.1)
Requirement already satisfied: soundfile>=0.12.1 in c:\users\administrator\appda
ta\local\programs\python\python310\lib\site-packages (from nonebot-plugin-ottohz
ys) (0.12.1)
Requirement already satisfied: numpy>=1.24.4 in c:\users\administrator\appdata\l
ocal\programs\python\python310\lib\site-packages (from nonebot-plugin-ottohzys)
(1.26.4)
Requirement already satisfied: pypinyin>=0.49.0 in c:\users\administrator\appdat
a\local\programs\python\python310\lib\site-packages (from nonebot-plugin-ottohzy
s) (0.51.0)
Requirement already satisfied: psola>=0.0.1 in c:\users\administrator\appdata\lo
cal\programs\python\python310\lib\site-packages (from nonebot-plugin-ottohzys) (
0.0.1)
Requirement already satisfied: anyio>=3.6.2 in c:\users\administrator\appdata\lo
cal\programs\python\python310\lib\site-packages (from nonebot-plugin-ottohzys) (
3.7.1)
Requirement already satisfied: httpx>=0.25.0 in c:\users\administrator\appdata\l
ocal\programs\python\python310\lib\site-packages (from nonebot-plugin-ottohzys)
(0.27.0)
Requirement already satisfied: async-lru>=2.0.4 in c:\users\administrator\appdat
a\local\programs\python\python310\lib\site-packages (from nonebot-plugin-ottohzy
s) (2.0.4)
Requirement already satisfied: idna>=2.8 in c:\users\administrator\appdata\local
\programs\python\python310\lib\site-packages (from anyio>=3.6.2->nonebot-plugin-
ottohzys) (3.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\administrator\appdata\lo
cal\programs\python\python310\lib\site-packages (from anyio>=3.6.2->nonebot-plug
in-ottohzys) (1.3.1)
Requirement already satisfied: exceptiongroup in c:\users\administrator\appdata\
local\programs\python\python310\lib\site-packages (from anyio>=3.6.2->nonebot-pl
ugin-ottohzys) (1.2.0)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\administrato
r\appdata\local\programs\python\python310\lib\site-packages (from async-lru>=2.0
.4->nonebot-plugin-ottohzys) (4.10.0)
Requirement already satisfied: certifi in c:\users\administrator\appdata\local\p
rograms\python\python310\lib\site-packages (from httpx>=0.25.0->nonebot-plugin-o
ttohzys) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\administrator\appdata\l
ocal\programs\python\python310\lib\site-packages (from httpx>=0.25.0->nonebot-pl
ugin-ottohzys) (1.0.4)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\administrator\appdata
\local\programs\python\python310\lib\site-packages (from httpcore==1.*->httpx>=0
.25.0->nonebot-plugin-ottohzys) (0.14.0)
Requirement already satisfied: arclet-alconna>=1.8.5 in c:\users\administrator\a
ppdata\local\programs\python\python310\lib\site-packages (from nonebot-plugin-al
conna>=0.40.0rc1->nonebot-plugin-ottohzys) (1.8.6)
Requirement already satisfied: arclet-alconna-tools>=0.7.0 in c:\users\administr
ator\appdata\local\programs\python\python310\lib\site-packages (from nonebot-plu
gin-alconna>=0.40.0rc1->nonebot-plugin-ottohzys) (0.7.1)
Requirement already satisfied: nepattern>=0.6.5 in c:\users\administrator\appdat
a\local\programs\python\python310\lib\site-packages (from nonebot-plugin-alconna
>=0.40.0rc1->nonebot-plugin-ottohzys) (0.6.5)
Requirement already satisfied: loguru<1.0.0,>=0.6.0 in c:\users\administrator\ap
pdata\local\programs\python\python310\lib\site-packages (from nonebot2>=2.2.0->n
onebot-plugin-ottohzys) (0.7.2)
Requirement already satisfied: pydantic!=2.5.0,!=2.5.1,<3.0.0,>=1.10.0 in c:\use
rs\administrator\appdata\local\programs\python\python310\lib\site-packages (from
 nonebot2>=2.2.0->nonebot-plugin-ottohzys) (1.10.14)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in c:\users\administrator\a
ppdata\local\programs\python\python310\lib\site-packages (from nonebot2>=2.2.0->
nonebot-plugin-ottohzys) (2.5.0)
Requirement already satisfied: python-dotenv<2.0.0,>=0.21.0 in c:\users\administ
rator\appdata\local\programs\python\python310\lib\site-packages (from nonebot2>=
2.2.0->nonebot-plugin-ottohzys) (1.0.1)
Requirement already satisfied: tomli<3.0.0,>=2.0.1 in c:\users\administrator\app
data\local\programs\python\python310\lib\site-packages (from nonebot2>=2.2.0->no
nebot-plugin-ottohzys) (2.0.1)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in c:\users\administrator\appd
ata\local\programs\python\python310\lib\site-packages (from nonebot2>=2.2.0->non
ebot-plugin-ottohzys) (1.9.4)
Requirement already satisfied: pypar in c:\users\administrator\appdata\local\pro
grams\python\python310\lib\site-packages (from psola>=0.0.1->nonebot-plugin-otto
hzys) (0.0.5)
Requirement already satisfied: tqdm in c:\users\administrator\appdata\local\prog
rams\python\python310\lib\site-packages (from psola>=0.0.1->nonebot-plugin-ottoh
zys) (4.66.2)
Requirement already satisfied: praat-parselmouth in c:\users\administrator\appda
ta\local\programs\python\python310\lib\site-packages (from psola>=0.0.1->nonebot
-plugin-ottohzys) (0.4.3)
Requirement already satisfied: cffi>=1.0 in c:\users\administrator\appdata\local
\programs\python\python310\lib\site-packages (from soundfile>=0.12.1->nonebot-pl
ugin-ottohzys) (1.16.0)
Requirement already satisfied: tarina>=0.4.4 in c:\users\administrator\appdata\l
ocal\programs\python\python310\lib\site-packages (from arclet-alconna>=1.8.5->no
nebot-plugin-alconna>=0.40.0rc1->nonebot-plugin-ottohzys) (0.4.4)
Requirement already satisfied: pycparser in c:\users\administrator\appdata\local
\programs\python\python310\lib\site-packages (from cffi>=1.0->soundfile>=0.12.1-
>nonebot-plugin-ottohzys) (2.21)
Requirement already satisfied: colorama>=0.3.4 in c:\users\administrator\appdata
\local\programs\python\python310\lib\site-packages (from loguru<1.0.0,>=0.6.0->n
onebot2>=2.2.0->nonebot-plugin-ottohzys) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\administrator\a
ppdata\local\programs\python\python310\lib\site-packages (from loguru<1.0.0,>=0.
6.0->nonebot2>=2.2.0->nonebot-plugin-ottohzys) (1.1.0)
Requirement already satisfied: multidict>=4.0 in c:\users\administrator\appdata\
local\programs\python\python310\lib\site-packages (from yarl<2.0.0,>=1.7.2->none
bot2>=2.2.0->nonebot-plugin-ottohzys) (6.0.5)

C:\Users\Administrator\Desktop\112\miraibot>
’‘’

**Comment by viondw** [comment]
```
PS C:\Users\Administrator\Desktop\112\miraibot> nb plugin install nonebot-plugin-ottohzys
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: nonebot-plugin-ottohzys in c:\users\administrator\appdata\local\programs\python\python310
\lib\site-packages (0.2.0)
Requirement already satisfied: nonebot2>=2.2.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\sit
e-packages (from nonebot-plugin-ottohzys) (2.2.1)
Requirement already satisfied: nonebot-plugin-alconna>=0.40.0rc1 in c:\users\administrator\appdata\local\programs\python
\python310\lib\site-packages (from nonebot-plugin-ottohzys) (0.41.1)
Requirement already satisfied: soundfile>=0.12.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\s
ite-packages (from nonebot-plugin-ottohzys) (0.12.1)
Requirement already satisfied: numpy>=1.24.4 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-
packages (from nonebot-plugin-ottohzys) (1.26.4)
Requirement already satisfied: pypinyin>=0.49.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\si
te-packages (from nonebot-plugin-ottohzys) (0.51.0)
Requirement already satisfied: psola>=0.0.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-p
ackages (from nonebot-plugin-ottohzys) (0.0.1)
Requirement already satisfied: anyio>=3.6.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-p
ackages (from nonebot-plugin-ottohzys) (3.7.1)
Requirement already satisfied: httpx>=0.25.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-
packages (from nonebot-plugin-ottohzys) (0.27.0)
Requirement already satisfied: async-lru>=2.0.4 in c:\users\administrator\appdata\local\programs\python\python310\lib\si
te-packages (from nonebot-plugin-ottohzys) (2.0.4)
Requirement already satisfied: idna>=2.8 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-pack
ages (from anyio>=3.6.2->nonebot-plugin-ottohzys) (3.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-p
ackages (from anyio>=3.6.2->nonebot-plugin-ottohzys) (1.3.1)
Requirement already satisfied: exceptiongroup in c:\users\administrator\appdata\local\programs\python\python310\lib\site
-packages (from anyio>=3.6.2->nonebot-plugin-ottohzys) (1.2.0)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\administrator\appdata\local\programs\python\python31
0\lib\site-packages (from async-lru>=2.0.4->nonebot-plugin-ottohzys) (4.10.0)
Requirement already satisfied: certifi in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packag
es (from httpx>=0.25.0->nonebot-plugin-ottohzys) (2024.2.2)
Requirement already satisfied: httpcore==1.* in c:\users\administrator\appdata\local\programs\python\python310\lib\site-
packages (from httpx>=0.25.0->nonebot-plugin-ottohzys) (1.0.4)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\administrator\appdata\local\programs\python\python310\lib\sit
e-packages (from httpcore==1.*->httpx>=0.25.0->nonebot-plugin-ottohzys) (0.14.0)
Requirement already satisfied: arclet-alconna>=1.8.5 in c:\users\administrator\appdata\local\programs\python\python310\l
ib\site-packages (from nonebot-plugin-alconna>=0.40.0rc1->nonebot-plugin-ottohzys) (1.8.6)
Requirement already satisfied: arclet-alconna-tools>=0.7.0 in c:\users\administrator\appdata\local\programs\python\pytho
n310\lib\site-packages (from nonebot-plugin-alconna>=0.40.0rc1->nonebot-plugin-ottohzys) (0.7.1)
Requirement already satisfied: nepattern>=0.6.5 in c:\users\administrator\appdata\local\programs\python\python310\lib\si
te-packages (from nonebot-plugin-alconna>=0.40.0rc1->nonebot-plugin-ottohzys) (0.6.5)
Requirement already satisfied: loguru<1.0.0,>=0.6.0 in c:\users\administrator\appdata\local\programs\python\python310\li
b\site-packages (from nonebot2>=2.2.0->nonebot-plugin-ottohzys) (0.7.2)
Requirement already satisfied: pydantic!=2.5.0,!=2.5.1,<3.0.0,>=1.10.0 in c:\users\administrator\appdata\local\programs\
python\python310\lib\site-packages (from nonebot2>=2.2.0->nonebot-plugin-ottohzys) (1.10.14)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in c:\users\administrator\appdata\local\programs\python\python310\l
ib\site-packages (from nonebot2>=2.2.0->nonebot-plugin-ottohzys) (2.5.0)
Requirement already satisfied: python-dotenv<2.0.0,>=0.21.0 in c:\users\administrator\appdata\local\programs\python\pyth
on310\lib\site-packages (from nonebot2>=2.2.0->nonebot-plugin-ottohzys) (1.0.1)
Requirement already satisfied: tomli<3.0.0,>=2.0.1 in c:\users\administrator\appdata\local\programs\python\python310\lib
\site-packages (from nonebot2>=2.2.0->nonebot-plugin-ottohzys) (2.0.1)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in c:\users\administrator\appdata\local\programs\python\python310\lib\
site-packages (from nonebot2>=2.2.0->nonebot-plugin-ottohzys) (1.9.4)
Requirement already satisfied: pypar in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages
 (from psola>=0.0.1->nonebot-plugin-ottohzys) (0.0.5)
Requirement already satisfied: tqdm in c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages
(from psola>=0.0.1->nonebot-plugin-ottohzys) (4.66.2)
Requirement already satisfied: praat-parselmouth in c:\users\administrator\appdata\local\programs\python\python310\lib\s
ite-packages (from psola>=0.0.1->nonebot-plugin-ottohzys) (0.4.3)
Requirement already satisfied: cffi>=1.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-pack
ages (from soundfile>=0.12.1->nonebot-plugin-ottohzys) (1.16.0)
Requirement already satisfied: tarina>=0.4.4 in c:\users\administrator\appdata\local\programs\python\python310\lib\site-
packages (from arclet-alconna>=1.8.5->nonebot-plugin-alconna>=0.40.0rc1->nonebot-plugin-ottohzys) (0.4.4)
Requirement already satisfied: pycparser in c:\users\administrator\appdata\local\programs\python\python310\lib\site-pack
ages (from cffi>=1.0->soundfile>=0.12.1->nonebot-plugin-ottohzys) (2.21)
Requirement already satisfied: colorama>=0.3.4 in c:\users\administrator\appdata\local\programs\python\python310\lib\sit
e-packages (from loguru<1.0.0,>=0.6.0->nonebot2>=2.2.0->nonebot-plugin-ottohzys) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\administrator\appdata\local\programs\python\python310\l
ib\site-packages (from loguru<1.0.0,>=0.6.0->nonebot2>=2.2.0->nonebot-plugin-ottohzys) (1.1.0)
Requirement already satisfied: multidict>=4.0 in c:\users\administrator\appdata\local\programs\python\python310\lib\site
-packages (from yarl<2.0.0,>=1.7.2->nonebot2>=2.2.0->nonebot-plugin-ottohzys) (6.0.5)
PS C:\Users\Administrator\Desktop\112\miraibot>
```

**Comment by XieXiLin2** [comment]
让你发加载日志，不是让你发安装日志（

**Comment by lgc2333** [comment]
![Image_1711538874040](https://github.com/lgc-NB2Dev/nonebot-plugin-ottohzys/assets/59048777/887b9dd5-9ab6-439a-8fa1-a5fa321a47f3)

**Comment by lgc2333** [comment]
看起来你是第一次在gh发issue，对昨天的无理感到抱歉……
issue被close是可以继续跟进的，只要admin没block这个issue
